---
MetricsTable:
  rpc: get-interface-information
  args:
    statistics: True
    detail: True
    interface_name: '[afgxe][et]-*' 
  args_key: interface_name
  item: physical-interface
  view: MetricsView

MetricsView:
  groups:
    flags: if-device-flags
    ts: traffic-statistics
    rxerrs: input-error-list
    txerrs: output-error-list

  fields:
    oper : { oper-status: flag }
    admin : { admin-status: flag }
    description: description
    mtu: { mtu : int }
    link_mode: link-mode
    speed: speed
    macaddr: current-physical-address
    flapped: { interface-flapped/@seconds: int }

  fields_flags:
    running: { ifdf-running: flag }
    present: { ifdf-present: flag }

  fields_ts:
    rx_bytes: { input-bytes: int }
    tx_bytes: { output-bytes: int }

  fields_rxerrs:
    input_errors: { input-errors: int }

  fields_txerrs:
    output_errors: { output-errors: int }